[tool.black]
line-length = 88
skip-string-normalization = false

[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 88
exclude = .git,__pycache__,venv*,.venv*,.mypy_cache,.pytest_cache
ignore = E203, W503
